### ISSUE TITLE
DPL-617 As GSU TL (Camillo G) I would like a report detailing all Heron post-cherrypicking destination plates still held in freezers so that the RVI project can plan.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/General-Backlog-Items#242] opened 2023-01-13 14:02 UTC
**Describe the Housekeeping**
As GSU TL (Camillo G) I would like a report detailing all Heron post-cherrypicking destination plates still held in freezers so that the RVI project can plan.

**Who the primary contacts are for this work**
Camillo G, Adrianne L

**Knowledge or Stake holders**
Camillo G, Adrianne L, Thomas W

**Additional context**
This is story comes from to RT 769749.

It is related to #211 

Can we produce an inventory report of the samples between the time period of 01/05/22 to date, aiming to get a break down of what is currently stored a month-by-month breakdown. 

Would it be possible to re-run Stuart’s data retrieval script for the destination plates in that range? 
We would require the following information to generate the report and a Month breakdown:

**To Be Answered:** Month to month breakdown by what date field? Min Date Tested, Date Received, Cherrypicked ???

·        Sampling dates from 01/05/22 – to date

·        Information to be included in the report:

o   Plate Purpose
This should include:
      ·        LHR RT were the original RT plates that sometimes came directly from CGaP and other times from samples sent by lighthouses.  These are from the very early stages of the pandemic.                                       
      ·        LTHR RT are the equivalent plates, but for tailed samples.                                                           
      ·        LHR Cherry-pick are the destination plates from cherry-picking using Beckman and Biosero
      ·        LTHR Cherry-pick are the tailed samples of the above

o   Plate Barcode

o   Sample Count

o   Min Date Tested.  This will be >= 01/05/22

o   Max Date Tested. This will be less than the reports run date.

o   Is sequenced. Did anything from the plate reach sequencing? True/False

o   Fully Qualified Location 

Related RT ticket [#769749](https://rt.sanger.ac.uk/Ticket/Display.html?id=769749)

**Comment by sdjmchattie** [comment] 2023-02-07 12:37
This is a duplicate of https://github.com/sanger/General-Backlog-Items/issues/240

**Closed** 2023-02-07 12:37 UTC
Labels: Research, RVI
