### ISSUE TITLE
GPL-954 Automated Kanban of Covid product from LIMS & NPG [Heron]

### ISSUE THREAD

**Issue by rl15** [sanger/General-Backlog-Items#140] opened 2021-04-01 10:31 UTC
User story
GPL-954 As a product lead (Sara S) I would like to visualise the inventory of plates in LIMS for the covid sequencing product into  QC and completed sequencing (into NPG tracking systems) to show state of operations real time end to end

Who are the primary contacts for this story
Sara S (Product lead ops)
Rich C
James M
Lee W (PAM)
James G (Prototype this idea previously)
Tom W (Prototype approach for UKB)

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] add a list of acceptance criteria here
- [ ] ...

**Dependencies**
Assumes GPL-953 done

**Additional context**

**Comment by rl15** [comment] 2021-04-12 09:47
See 

- iseq_run_status and associated
- iseq_run_status_dict

Tables in MLWH

**Comment by TWJW-SANGER** [comment] 2021-04-20 16:35
Matt Francis has produced a Kanban Tableau report for NPG run status - have seen it but don't have link...,

**Comment by TWJW-SANGER** [comment] 2023-02-09 10:24
Duplicate of Kanban board now delivered in Limber

**Closed by TWJW-SANGER** 2023-02-09 10:24 UTC
Labels: Reporting
