### ISSUE TITLE
GPL-926 Housekeeping - training environment link to warehouses (E:L, V:3)

### ISSUE THREAD

**Issue by KatyTaylor** [sanger/General-Backlog-Items#127] opened 2021-03-23 15:41 UTC
**Describe the Housekeeping**
The Sequencescape training environment should link to the Multi-LIMS and Event warehouses. We use training as an environment in which to test data fixes, because it has a copy of production data. It would be a more useful and thorough test setup if the effect of those data fixes could be seen on the warehouses.

The warehouse consumers should be linked to databases that contain regularly refreshed production data - perhaps mlwhd_mlwh_events_proddata and mlwhd_mlwarehouse_proddata.
Be aware that Sequencescape UAT currently sends messages to mlwhd_mlwh_events_proddata - there is an issue to change this here - https://github.com/sanger/event_warehouse/issues/117

**Additional context**
This came out of the UKB data fixes - https://github.com/sanger/General-Backlog-Items/issues/120 - as something that would make it quicker next time.
The workaround used for that was to set up a RabbitMQ server and the Sequencescape / MLWH / Events WH consumers locally, pointing to the sequencescape_snapshot and mlwhd_mlwh_events_proddata databases, which took 3 full days, and ran very slowly.

**Comment by TWJW-SANGER** [comment] 2023-08-31 09:25
Appears to be a duplicate of #336

**Closed** 2024-08-16 08:17 UTC
