### ISSUE TITLE
Y24-036 [BUG] Prevent automated releases workflow from deleting stable release docker images [Should've]

### ISSUE THREAD

**Issue by BenTopping** [sanger/General-Backlog-Items#378] opened 2024-03-25 14:19 UTC
**Describe the bug**
In our docker projects we have a github action automated_release.yml which deletes old docker images. We want to update this action to only delete non-stable/develop images as it is currently deleting stable releases which means we can end up without a production-ready release. This is dangerous in the case we need to do an emergency redeploy or rollback to an old image.

**Acceptance Criteria**

- [ ] Update the automated_release.yml action in all docker repositories so it doesn't delete stable releases.

**Expected behaviour**
We expect this to only delete non-stable/develop images.

**Contacts**
Abdullah Y, Ben T

**Additional context**
https://github.com/search?q=org%3Asanger+automated_release.yml&type=code Might be useful when searching for affected repositories.

**Comment by SHIV5T3R** [comment] 2024-04-12 10:30
This _should_ be affecting other repos, but for some (for example, SequenceScape), the action isn't running as intended at all. I pushed a fix for print_my_barcode, I'll have a look at why this stopped running for the other apps.

**Closed** 2024-04-12 14:03 UTC
Labels: Bug, Size: S, Value: 4, Housekeeping
